### ISSUE TITLE
Problem with images

### ISSUE THREAD

**Issue by ofoe0002** [ofoe0002/mtm6201-week1#2]
@abhaysharma Good day, professor. I've been working on my assignment and I'm pretty much finished. The only issue I have is when I try to sync, the images don't load when I check the pages. I've tried putting it in a folder, using different file paths...nothing's worked so far. I also have a css folder with an external css file and that works fine so I don't know what's going on with the image. I would really appreciate your help with this, thanks!

**Comment by abhaysharma** [comment]
@ofoe0002 there are a few issues with your image path and name
1. Your file name must be all lowercase and without any spaces
2. Your path should start with images/ and not with ../image

**Comment by ofoe0002** [comment]
Everything works fine now, thank you professor!
